name: example_nav2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  effective_dart: 1.3.1
  # get: ^4.1.4
  get:
    path: ../
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^19.3.59
  dart_lol:
    path: ../../dart_lol
  # dart_lol: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
